### ISSUE TITLE
Include URL and page content in the Topics classifier features

### ISSUE THREAD

**Issue by lbdvt** [patcg-individual-drafts/topics#118]
The Topics classifier currently uses only the page hostname to define the corresponding topics.

This leads to large sites, with diverse content, getting a very generic topic with low advertising value.

Taking into account the URL and the content of the website as features in the classifier will allow for much more accurate classification of websites’ pages and shall improve the signaling within Topics.

**Comment by dmarti** [comment]
This probably needs a separate permission. In many cases the page content or path can be sensitive when the domain is not.  (It's possible that a user would be perfectly fine with having the `drugstore.example` domain used for training, but not the content of `drugstore.example/my-orders`)

**Comment by jkarlin** [comment]
Exposing content beyond the origin to the API is tricky from a privacy perspective. Cross-origin iframes today do not have access to the page title or URL or page contents, just the origin. Giving Topics access to that data means it's possible for these third-parties to then learn topics inferred from content they couldn't otherwise access. It's quite limited data, but enough that it gives pause and would likely need some mitigations to protect against abuse. As such, closing for now as we don't intend to do this in the near future.

**Comment by patmmccann** [comment]
@jkarlin it seems the concern you express only applies in a default state. By making access to the extra information opt-in via permissions, you wouldn't allow the cross-origin iframe access to information it couldn't gather today through, for example, an opt-in post message orchestrated by the publisher.

**Comment by jkarlin** [comment]
#224 has continued discussion on a possible opt-in mechanism.
