### ISSUE TITLE
"Status of this document" is empty

### ISSUE THREAD

**Issue by domenic** [patcg-individual-drafts/topics#175]
On https://patcg-individual-drafts.github.io/topics/ .

Traditionally for CG drafts this contains some boilerplate that might be important. Compare, e.g., https://wicg.github.io/close-watcher/ .

This is probably a more general problem with patcg-individual-drafts? Maybe solved by making changes to https://github.com/speced/bikeshed-boilerplate ? Not sure.

**Comment by chrisn** [comment]
This is important. The Readme clearly states:

> This document is an individual draft proposal. It has not been adopted by the Private Advertising Technology Community Group.

so at a minimum this needs to be reflected in the draft spec itself.

I would also argue that because this draft has not been adopted by PATCG (and nor is it a WICG spec), it should also not carry the W3C logo and branding. This has the potential to cause wider confusion over the spec's standardisation status.

**Comment by xyaoinum** [comment]
This should have been fixed in https://github.com/patcg-individual-drafts/topics/pull/234
