### ISSUE TITLE
What should happen if a site disagrees with the topics assigned to it by the browser?

### ISSUE THREAD

**Issue by jkarlin** [patcg-individual-drafts/topics#2]
Should there be a process to alter the assignment? What should the process be? 

An alternative is to allow for sites to set their own topics via response header, as in #1.

**Comment by dmarti** [comment]
Or a site could take pages that are causing its topics to be misidentified and put them in their own section: #17. That way the classifier can still classify them, but their off-topic topics don't affect the top-level topics for the site.

**Comment by Marthajorgeesteban** [comment]
// document.browsingTopics() returns an array of up to three topic objects in random order.
const topics = await document.browsingTopics();

// The returned array looks like: [{'configVersion': String, 'modelVersion': String, 'taxonomyVersion': String, 'topic': Number, 'version': String}]

// Get data for an ad creative.
const response = await fetch('https://ads.example/get-creative', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
  },
  body: JSON.stringify(topics)
});
// Get the JSON from the response.
const creative = await response.json();

// Display ad.

**Comment by Marthajorgeesteban** [comment]
https://ads.example/get-creative

**Comment by jkarlin** [comment]
Mislabeled topics can degrade the quality of the user's topics on other sites, and we wish to iteratively improve on the classifier, but providing overrides via the platform seems to open more problems (e.g., intentionally incorrect topics) than it's worth. Note that mislabeled topics should not bring harm to the mislabeled site itself, as the site can provide its own contextual information to buyers.

**Comment by dmarti** [comment]
Patterns of repeatable mislabeling -- which can be recognized and trained on by server-side ML but not by individual users without significant cooperative research -- are examples of Topics API working normally in cooperation with server-side ad decisioning. The mislabeling is not a priority to fix in the browser because a known pattern of mislabeling can be trained around on a server that has sufficient data.

Topics API is a way for a browser to pass an obfuscated cohort identifier to a classifier on a server -- it's essentially FLoC, but the mystery numbers are in base 629 instead of base 10.

An individual user can't understand what Topics API cohort Google's ML has assigned you to just based on the individual topics in the set -- that's like saying you know what your FLoC cohort means because you know the digits 0-9.

Without access to the server it's hard to say whether mislabeling different sites about the same topic differently actually provides more info to the server-side logic about the user's cohort membership than correct labeling would. Allowing sites to correct their topics at arbitrary times could make server-side ML less useful.

**Comment by Safwanni2212** [comment]
👍👍👍👍👍👍👍❤️

👍
