### ISSUE TITLE
Lack of prompts to alert users that they are being observed topics

### ISSUE THREAD

**Issue by hmmhmmhm** [patcg-individual-drafts/topics#222]
I propose that a notification should be implemented to inform users that their topics are under the website's scrutiny. Additionally, the reason behind the website's interest in the user's individual likes or preferences should be articulated clearly in a manner that the user can comprehend easily.

For instance, if a personal blog randomly get five interests from my entire interest list, I do not find it very convincing. In fact, most users might resent this and promptly opt to disable the feature.

Currently, information is categorized into major and minor sections. On this premise, how about we introduce a procedure where the user initiates a request for the major category that the website wishes to collect. Afterwards, the user would receive a prompt asking for their affirmation on the data collection.

**Comment by michaelkleber** [comment]
> I propose that a notification should be implemented to inform users that their topics are under the website's scrutiny.

I believe Chrome shows a browser-level indication when the precise geolocation API is used, but as far as I know that's the only thing with that level of heightened sensitivity attached to it.

> Additionally, the reason behind the website's interest in the user's individual likes or preferences should be articulated clearly in a manner that the user can comprehend easily.

This would be up to the party calling the API, not up to the browser.  We expect the API to be used for choosing which ads to show, and that is how we clearly describe the API in our settings and documentation.  But if you're interested in what different websites do differently, you would need to ask the website, since the browser cannot distinguish.

> For instance, if a personal blog randomly get five interests from my entire interest list, I do not find it very convincing.

I'm not sure what you mean by this, but "randomly get five interests from my entire interest list" is not any part of how the API works.
