### ISSUE TITLE
First-party Leagues Implementing the Governed Harvesting of Topics (FLIGHT)

### ISSUE THREAD

**Issue by darobin** [patcg-individual-drafts/topics#28]
This issue was spawned from an [earlier Twitter discussion](https://twitter.com/Log3overLog2/status/1486472087984353288?s=20).

## The problem
As currently proposed, Topics are available based on where specific 3Ps are present. This gating creates several issues:
* The rich get richer: 3Ps with a presence on the greatest number of sites are more likely to benefit than those with a small presence. In a competitive bidding environment, the entrenchment effects are likely to be strong.
* Arbitrary value transfer: sites that are good predictors of valuable topics transfer value to sites that aren't based simply on having selected the same provider. This type of fungibility makes it more profitable to produce low-quality content (if not worse) and monetise thanks to others' high quality work, than to produce high quality work. First parties should have an active say in who they share their work with.
* No incentive to monitor bad actors: 3Ps are incentivised to work with as many 1Ps as possible, 1Ps are incentivised to work with the 3Ps that have the most other 1Ps. This removes incentives (and, for the 1P, responsibility) to exclude bad actors that rely on the shared distribution of value to produce hate or disinformation.

## Approach
I am deliberately not proposing a technical mechanism at this point, but rather focusing on the desirable outcomes first.

The idea is that instead of gating the shared elaboration of Topics through whoever happens to have the same 3P, it is done through explicit groups (leagues) of first-parties. Behaviour on any member of a given league contributes to the elaboration of topics that can be used for IG targeting on any other. This has several consequences:

* It encourages collaboration across first parties, making groups of any size with whatever internal rules they wish to have.
* It avoids structurally anticompetitive effects.
* First parties get to choose who they share value with, meaning they can deploy values-based choices to the inclusion or exclusion of actors that intermediaries struggle with.
* Presumably, a form of league identifier would be included in bids. This would enable bidders to assess topic quality (and some leagues will provide a better signal for specific topics) as well as brand safety (it's easier to filter out leagues that accept hate and disinfo).
* Local monitoring: league members have a shared interest in the quality of their league as represented to bidders, and therefore are encouraged to check that other members aren't misbehaving. (Monitoring is a key function of commons.) This can help move away from the dynamic in which intermediaries are bad at monitoring and enforcement (for whatever reasons) and other actors have no leverage other than complaining.
* It provides a logical and useful place off of which to potentially hang custom topic classification models, specific taxonomies, or various approaches to elaborating more precise topics (eg. a shared model that is simply used to push topics into a `meta`).

In order for this to work, a league would have to be something that you can't join at high speed or frequency. This is significantly more complex than gating on origin and a method call; my assumption is that whatever technical mechanism underlies topic leagues would be shared with _other_ approaches that also benefit from grouping first parties for whatever reason.

I realise this is more hand waving than the usual fare (though maybe by waving hands fast enough one may… take flight) but I'm trying to hold off jumping into solution space while we discuss the potential value of the overall approach.

**Comment by darobin** [comment]
Adding a note from @lukwlodarczyk (which [he wrote here](https://twitter.com/luk_wlodarczyk/status/1486800470077227010?s=20&t=mnJH-71QY-rz8dmYaISrZg)): this approach could also help avoid the disutility produced by having too many people have broad, boring categories as their top topics, which would be low-value in targeting.

**Comment by darobin** [comment]
And Wayne Blodwell also had [some questions that were discussed elsewhere](https://twitter.com/wayneblodwell/status/1486774828954800131?s=20&t=mnJH-71QY-rz8dmYaISrZg).

**Comment by michaelkleber** [comment]
Thank you for opening this.  While I see a lot to like about this idea, I want to be sure we're on the same page about all the problems we would need to solve to make this viable.  This is surely not an exhaustive list, but some initial concerns:

**Privacy thoughts**

1. *Exclusivity:* We can only make one source of Topics available on a given website — two sources would put us right back into fingerprinting-risk territory.  These in-league Topics would be _replacing,_ not supplementing, the global Topics in the proposal.  (Well, I guess there could be an "Unaffiliated" league of everyone left over?)  So these affiliations are a partitioning of the web into non-overlapping Topic League zones.

1. *Browsing History Leak:* If a league only has one site on a particular Topic, then revealing that Topic for a user is giving away a specific visit in their browsing history.  This risk is much more acute for a closed-world domain than for the web-wide case with many sites on each Topic.

1. *Topic Meaning:* A closed set of sites also runs the risk of a particular Topic meaning something other than what it says on the tin.  Of course the meaning of "/Hobbies & Leisure/Outdoors" could be subtly different in league A vs B, but there's also the risk that that topic is used in some league as a codeword to represent something sensitive — and this also circumvents the browser controls which are trying to provide transparency.

**Utility thoughts**

4. *League hit rate:* If a league is small, then it seems likely that many people only visit one or two of its member sites, and the in-league Topics signal is useless.  Actually "small" isn't even the risk here; I'd guess a large coherent group like "all local newspaper sites" would have a similarly low hit rate.  As other issues have pointed out, leagues that didn't cross the advertiser/publisher boundary might struggle.

4. *Governance:* Of course someone will need to decide who is allowed in a league, and since a league has a lot of sites in it, that will be a lot of work.  You described the problem of "intermediaries are bad at monitoring and enforcement (for whatever reasons) and other actors have no leverage other than complaining", and this could trigger the very same dynamic.  I expect your response is that it's easier for a disgruntled site to vote with its feet, i.e. it's easier to change leagues than ad networks.  But—

4. — would ad networks stay agnostic about choice of league membership?  It seems easy for an ad network to say that it only has ML models that understand Topics from a small number of leagues.


Everything here may be solvable, don't get me wrong!  But these do seem like a bunch of risks that are substantially elevated compared to a web-wide notion of Topics.

**Comment by jkarlin** [comment]
Note that the existing proposal does allow for league creation. Each league agrees upon a third-party that they use the Topics API with, and they'll share their knowledge about the user's topics across their sites. But it wouldn't be _exclusively_ league based, which I think is another one of your asks.

**Comment by jkarlin** [comment]
Closing. Feel free to reopen if there is more to discuss.
