### ISSUE TITLE
Product sale only, or is job advertising considered?

### ISSUE THREAD

**Issue by rsolberg1** [patcg-individual-drafts/topics#35]
The taxonomy_v1 file proposes interests which seems to work just fine with product sale. Do you have any thoughts on how topics may work with job advertising? A user browsing pattern which emerges from the fact that you are in the state of a career/job change is not alone based on a categorization of interests.

**Comment by dialtone** [comment]
I would expand this to say that there are many areas of advertising not well covered by the categories. For example B2B advertising would look at more resolution on those topics that businesses may care about vs a simple "Software", for example "CDN" or "SSO" or "Network Security" is the only computer security related tag.

**Comment by rsolberg1** [comment]
I would strongly suggest someone to take a look at what's called the "Internation Standard Classification of Occupations", also referenced as ISCO-08. It's an international standard. Basically a hierarchy of codes from 0-9999 organized much in the same way as in the taxonomy_v1 file - if you flatten out the data. It eliminates the requirement of inventing something new regarding to job advertising and topics. Even so, the complex part would still remain to figure out. Which kind of mechanisms should be in play for registering such topics in the browser.

**Comment by jkarlin** [comment]
Hey folks. To be clear, we understand that the initial taxonomy has its flaws. For instance, it only contains ~half of the IAB's taxonomy that we referenced. And the ones it contains are chosen because they intersect with Google's ads taxonomy (which meant that we had training data for it and sensitivity analysis from two different entities). 

Looking forward, we'd like to see the industry rally around a taxonomy that represents the interests of many parties, has serious sensitivity validation in place, and ideally provides training data or classifiers available for browsers to incorporate.
