### ISSUE TITLE
Question for g.doubleclick.net not in chrome://topics-internals/

### ISSUE THREAD

**Issue by relevance-api-topics** [patcg-individual-drafts/topics#352]
Hi Topics API experts,

We are trying to understand detailed usage observation of Topics API, and seems even from Networking tab, there is a call sent and caught, within chrome://topics-internals/ there is no observer recorded, is this expected? thanks.

e.g:
<img width="1209" alt="google-check-1" src="https://github.com/user-attachments/assets/af7979bf-7388-4566-aa1a-6347058edad4">

A quick note is that as suggested we will add more details into our account to ensure there is no concern from your side, but if it is not required we would prefer it to be totally open-sourced eco-system:) thanks!

**Comment by michaelkleber** [comment]
> We are trying to understand detailed usage observation of Topics API, and seems even from Networking tab, there is a call sent and caught, within chrome://topics-internals/ there is no observer recorded, is this expected?

When using the HTTP header mechanism to interact with the Topics API, the topics are sent in the `Sec-Browsing-Topics` request header, but they are only observed if the server replies with the `Observe-Browsing-Topics: ?1` response header.  See all the details in [this part](https://github.com/patcg-individual-drafts/topics#:~:text=topics%20can%20also%20be%20retrieved%20via%20request%20headers%2C%20and%20marked%20as%20observed%20and%20eligible%20for%20topics%20calculation%20via%20response%20headers) of the explainer.

> A quick note is that as suggested we will add more details into our account to ensure there is no concern from your side, but if it is not required we would prefer it to be totally open-sourced eco-system:)

This repository is for the ongoing work to design a browser API, under the auspices of the W3C's [Private Advertising Technology Community Group](https://www.w3.org/community/patcg/).  Contributions to that effort are subject to the W3C Community [Contributor License Agreement](https://www.w3.org/community/about/process/cla/), an essential part of the protections that ensure acceptable licensing rights for the work that comes out of the web standards process.  This is how you _make_ something an open-source ecosystem.

If you don't want to identify yourself as part of an organization that has entered into that legal agreement, then we cannot let you contribute to this group's work.  You can consider asking questions in our [Privacy Sandbox Developer Support](https://github.com/privacysandbox/privacy-sandbox-dev-support) forum, if you're just looking for understanding and documentation, rather than contributing to ongoing design discussions.
