### ISSUE TITLE
Topics performance and measurement

### ISSUE THREAD

**Issue by BasileLeparmentier** [patcg-individual-drafts/topics#52]
With Floc, it was possible to measure ad performance as the Floc ID was the same on the publisher and the advertiser website. It was less efficient than with cookies, and less precise, but it was at least possible to do something at the floc cohort level.

How does topic interact with the different measurement proposals? Indeed, the topics will not be the same across the publisher and advertiser website.

Did you think about how measurement is supposed to work with topics, especially at the discovery phase (which topics are the most suited for a given  ads)

**Comment by michaelkleber** [comment]
You are quite right that cohort measurement won't work with Topics in the way it might have with FLoC.  With Topics it seems like there are at least two natural approaches to consider:

1. Measure performance with your favorite part of the [Attribution Reporting API](https://github.com/WICG/conversion-measurement-api#attribution-reporting-api) to infer the contribution from the Topics that were visible at the time the ad was chosen.

2. Observe the Topics of (existing and/or new) customers, since each of those will be the Topics for your customers on around 1/5 of the other websites they visit.

The second of these seems particularly relevant to your "discovery phase" question.
